export const UPDATE_RECOMMEND_PLAYLIST = "PERSONAL_RECOMMEND/UPDATE_RECOMMEND_PLAYLIST";
export const UPDATE_PRIVATE_CONTENT = "PERSONAL_RECOMMEND/UPDATE_PRIVATE_CONTENT";
export const UPDATE_LASTEST_MUSIC = "PERSONAL_RECOMMEND/UPDATE_LASTEST_MUSIC";
export const UPDATE_RECOMMEND_MV = "PERSONAL_RECOMMEND/UPDATE_RECOMMEND_MV";
export const UPDATE_DJ_PROGRAM = "PERSONAL_RECOMMEND/UPDATE_DJ_PROGRAM"